version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ../db_data/postgres:/var/lib/postgresql/data
    networks:
      - ragtools_network

  neo4j:
    image: neo4j:latest
    container_name: ${NEO4J_CONTAINER_NAME}
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    volumes:
      - ../db_data/neo4j:/data
    networks:
      - ragtools_network

  ollama:
    image: ollama/ollama
    container_name: ${OLLAMA_LLM_CONTAINER_NAME}
    environment:
      - OLLAMA_HOST=0.0.0.0:${OLLAMA_LLM_PORT}
    ports:
      - "${OLLAMA_LLM_PORT}:${OLLAMA_LLM_PORT}"
    volumes:
      - ${OLLAMA_MODELS_PATH}:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
              capabilities: [gpu]
    networks:
      - ragtools_network

networks:
  ragtools_network:
    name: ${DOCKER_NETWORK_NAME}

volumes:
  postgres_data:
  neo4j_data:
  ollama_data: